Fix missing config file.

diff --git a/src/mokey b/src/mokey
--- a/src/mokey
+++ b/src/mokey
@@ -18,10 +18,32 @@ function permissions_check () {
 
 	# Exit script with permission problems.
 	test "$(id -u)" -eq "0" || {
-		echo "${_name}: root permission is required!"
+		echo "${_name}: root permission is required!" 1>&2
 		exit 1
 	}
 
+}
+
+function mokey_config_fix () {
+
+	local _download="https://raw.githubusercontent.com/mschaecher78/$_name/main/src$_cnf"
+
+	# If mokey is not installed byway of a package manager then make wget is installed and if the
+	# application is missing then error with command not found.
+	which wget &> /dev/null && {
+
+		# If for some reason the config file couldn't be downloaded; panic.
+		wget -c "$_download" -O $_cnf  &> /dev/null && {
+			echo "$_name: installing $_cnf"
+		} || {
+			echo "$_name: error downloading $_download!" 1>&2
+			exit 1
+		}
+
+	} || {
+		echo "$_name: requires wget for 'configure --fix' to function!" 1>&2
+		exit 126
+	}
 }
 
 set -e		# Allows exit as soon as an exit error code is passed, e.i. `exit 1` or `exit 126`.
@@ -112,11 +134,11 @@ EOF
 # Eventhough mokey comes with a config file that is used for openssl commands, still check that it exists and has
 # not been deleted. However this does't mean that mokey needs to be reinstalled, just fixed.
 test -f "$_config" || {
-	_array=( "configure" "help" "version" )				# Array of allowed pass through.
+	_array=( "config" "help" "version" )				# Array of allowed pass through.
 
 	# Anything that does not match with variable _a then that function is not allowed.
 	[[ ! " ${_array[*]}" =~ $1 ]] && {
-		echo -e "${_name}: missing config file, please run \`sudo ${_name} configure --fix\`!"
+		echo -e "${_name}: missing config file, please run \`sudo ${_name} configure --fix\`!" 1>&2
 		exit 1
 	}
 
@@ -125,6 +147,19 @@ test -f "$_config" || {
 # Because there are many different option that can be use, the use a `while loop`, getopt is not needed for this to work.
 # Besides getopt just adds more complication to an already complicated script.
 while true ; do case "$1" in
-	"help"			)	echo "${_usage}" ;;
-	"version"		)	echo -e "${_info}\n\n${_license}" ;;
+	"config"		)	permissions_check ; _command="mokey_config" ;;
+	"help"			)	echo "${_usage}" ; break ;;
+	"version"		)	echo -e "${_info}\n\n${_license}" ; break ;;
+	"--fix"			)
+
+		# Make sure that --fix option only works with config command.
+		test "$_command" = "mokey_config" && _command="${_command}_fix" || {
+			echo "$_name: '--fix' option only works with 'config' command!" 1>&2
+			exit 1
+		}
+
+	;;
 esac ; shift ; test -z "$1" && break ; done
+
+# Run command or exit if command is not present.
+${_command} || { echo "${_name}: missing command!" 1>&2 ; exit 126 ; }
